-- MySQL Script generated by MySQL Workbench
-- Mon Feb 19 13:05:46 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Student Record
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Student Record
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `Student Record` DEFAULT CHARACTER SET utf8 ;
USE `Student Record` ;

-- -----------------------------------------------------
-- Table `Student Record`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Student Record`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Student Record`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Student Record`.`Student` (
  `St_ID` INT NOT NULL,
  `F_Name` VARCHAR(45) NULL,
  `L_Name` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`St_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Student Record`.`Prof`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Student Record`.`Prof` (
  `Prof_ID` INT NOT NULL,
  `F_Name` VARCHAR(45) NULL,
  `L_Name` VARCHAR(45) NULL,
  PRIMARY KEY (`Prof_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Student Record`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Student Record`.`Department` (
  `Department_ID` INT NOT NULL,
  `Department_Name` VARCHAR(45) NULL,
  PRIMARY KEY (`Department_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Student Record`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Student Record`.`Course` (
  `Course_ID` INT NOT NULL,
  `Course_Name` VARCHAR(45) NULL,
  `Department_Department_ID` INT NOT NULL,
  `Prof_Prof_ID` INT NOT NULL,
  PRIMARY KEY (`Course_ID`),
  INDEX `fk_Course_Department_idx` (`Department_Department_ID` ASC),
  INDEX `fk_Course_Prof1_idx` (`Prof_Prof_ID` ASC),
  CONSTRAINT `fk_Course_Department`
    FOREIGN KEY (`Department_Department_ID`)
    REFERENCES `Student Record`.`Department` (`Department_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Course_Prof1`
    FOREIGN KEY (`Prof_Prof_ID`)
    REFERENCES `Student Record`.`Prof` (`Prof_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Student Record`.`Enrollment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Student Record`.`Enrollment` (
  `Student_St_ID` INT NOT NULL,
  `Course_Course_ID` INT NOT NULL,
  INDEX `fk_Enrollment_Student1_idx` (`Student_St_ID` ASC),
  INDEX `fk_Enrollment_Course1_idx` (`Course_Course_ID` ASC),
  CONSTRAINT `fk_Enrollment_Student1`
    FOREIGN KEY (`Student_St_ID`)
    REFERENCES `Student Record`.`Student` (`St_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Enrollment_Course1`
    FOREIGN KEY (`Course_Course_ID`)
    REFERENCES `Student Record`.`Course` (`Course_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Student Record`.`Textbook`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Student Record`.`Textbook` (
  `Book_ID` INT NOT NULL,
  `Title` VARCHAR(45) NULL,
  `Course_Course_ID` INT NOT NULL,
  PRIMARY KEY (`Book_ID`),
  INDEX `fk_Textbook_Course1_idx` (`Course_Course_ID` ASC),
  CONSTRAINT `fk_Textbook_Course1`
    FOREIGN KEY (`Course_Course_ID`)
    REFERENCES `Student Record`.`Course` (`Course_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
